// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeeBex6h-3dhKOsM2OCTpx-LC9s4FxhzA',
    appId: '1:1064757638020:web:6adb7fd00e887ffab3e3d1',
    messagingSenderId: '1064757638020',
    projectId: 'projecttwo-f3f71',
    authDomain: 'projecttwo-f3f71.firebaseapp.com',
    storageBucket: 'projecttwo-f3f71.firebasestorage.app',
    measurementId: 'G-WT16C4R255',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6zNvrG2BtYKqTZqIVffLWHoMosm8wZz0',
    appId: '1:1064757638020:android:7a66f1d53bd1aaaab3e3d1',
    messagingSenderId: '1064757638020',
    projectId: 'projecttwo-f3f71',
    storageBucket: 'projecttwo-f3f71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvcVznmZocEoFZJxHfrznm_6B_tXnabVE',
    appId: '1:1064757638020:ios:b1a5f5e798a1b7f0b3e3d1',
    messagingSenderId: '1064757638020',
    projectId: 'projecttwo-f3f71',
    storageBucket: 'projecttwo-f3f71.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvcVznmZocEoFZJxHfrznm_6B_tXnabVE',
    appId: '1:1064757638020:ios:b1a5f5e798a1b7f0b3e3d1',
    messagingSenderId: '1064757638020',
    projectId: 'projecttwo-f3f71',
    storageBucket: 'projecttwo-f3f71.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeeBex6h-3dhKOsM2OCTpx-LC9s4FxhzA',
    appId: '1:1064757638020:web:09083f2d5aaf733cb3e3d1',
    messagingSenderId: '1064757638020',
    projectId: 'projecttwo-f3f71',
    authDomain: 'projecttwo-f3f71.firebaseapp.com',
    storageBucket: 'projecttwo-f3f71.firebasestorage.app',
    measurementId: 'G-829RREFLB1',
  );
}
